In [2]:
import pandas as pd

In [3]:
df_laptop = pd.read_csv('laptop_price.csv' ,encoding='latin-1')

In [4]:
df_laptop.shape

(1303, 13)

In [5]:
print(df_laptop.columns)

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [6]:
df_laptop.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
7,8,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,1158.70
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Nvidia GeForce MX150,Windows 10,1.3kg,1495.00
9,10,Acer,Swift 3,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.6kg,770.00

In [7]:
df_laptop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [8]:
df_laptop.describe().round(2)

       laptop_ID   Inches  Price_euros
count    1303.00  1303.00      1303.00
mean      660.16    15.02      1123.69
std       381.17     1.43       699.01
min         1.00    10.10       174.00
25%       331.50    14.00       599.00
50%       659.00    15.60       977.00
75%       990.50    15.60      1487.88
max      1320.00    18.40      6099.00

In [9]:
df_laptop['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [10]:
df_laptop['Company'].value_counts(normalize=True).round(5)

Company
Dell         0.22794
Lenovo       0.22794
HP           0.21028
Asus         0.12126
Acer         0.07905
MSI          0.04144
Toshiba      0.03684
Apple        0.01612
Samsung      0.00691
Razer        0.00537
Mediacom     0.00537
Microsoft    0.00460
Xiaomi       0.00307
Vero         0.00307
Chuwi        0.00230
Google       0.00230
Fujitsu      0.00230
LG           0.00230
Huawei       0.00153
Name: proportion, dtype: float64

In [11]:
df_laptop['Company']=='Lenovo'

0       False
1       False
2       False
3       False
4       False
        ...
1298     True
1299     True
1300     True
1301    False
1302    False
Name: Company, Length: 1303, dtype: bool

In [12]:
apple = df_laptop['Company']=='Apple'
df_laptop[apple].head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97

In [13]:
apple = df_laptop['Company']=='Apple'
df_laptop[apple].describe().round(2)

       laptop_ID  Inches  Price_euros
count      21.00   21.00        21.00
mean      304.14   13.25      1564.20
std       478.10    1.24       561.62
min         1.00   11.60       898.94
25%         8.00   12.00      1163.00
50%        27.00   13.30      1339.69
75%       275.00   13.30      1958.90
max      1252.00   15.40      2858.00

In [14]:
df_laptop[df_laptop['Company']=='Apple'].value_counts('Company')

Company
Apple    21
Name: count, dtype: int64

In [15]:
df_laptop[df_laptop['Company'] == 'Apple'].head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97

In [16]:
df_laptop[df_laptop['Price_euros']>1]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [17]:
df_laptop['Price_euros']>3000

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Name: Price_euros, Length: 1303, dtype: bool

In [18]:
df_laptop['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [19]:
df_laptop[df_laptop['Company'] == 'Apple'].value_counts('Company')

Company
Apple    21
Name: count, dtype: int64

In [20]:
df_laptop['Company']!='HP'

0        True
1        True
2       False
3        True
4        True
        ...
1298     True
1299     True
1300     True
1301    False
1302     True
Name: Company, Length: 1303, dtype: bool

In [21]:
df_laptop[df_laptop['Company']!='HP'].value_counts('Company')

Company
Lenovo       297
Dell         297
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [27]:
df_laptop['Price_euros'].describe()

count    1303.000000
mean     1123.686992
std       699.009043
min       174.000000
25%       599.000000
50%       977.000000
75%      1487.880000
max      6099.000000
Name: Price_euros, dtype: float64

In [23]:
df_laptop.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [ ]:
df_laptop['Price_euros']>1487

0       False
1       False
2       False
3        True
4        True
        ...
1298    False
1299     True
1300    False
1301    False
1302    False
Name: Price_euros, Length: 1303, dtype: bool

In [38]:
df_laptop[df_laptop['Price_euros']>1487]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Nvidia GeForce MX150,Windows 10,1.3kg,1495.00
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1249,1267,Dell,XPS 13,2 in 1 Convertible,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i5 7Y54 1.2GHz,8GB,256GB SSD,Intel HD Graphics 615,Windows 10,1.24kg,1813.00
1256,1274,Asus,Rog G752VT-GC073T,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 970M,Windows 10,4.0kg,1900.00
1271,1289,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1285,1303,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00

In [37]:
df_laptop[df_laptop['Price_euros']>1487].value_counts()

laptop_ID  Company  Product                             TypeName            Inches  ScreenResolution                            Cpu                          Ram   Memory                Gpu                        OpSys       Weight  Price_euros
4          Apple    MacBook Pro                         Ultrabook           15.4    IPS Panel Retina Display 2880x1800          Intel Core i7 2.7GHz         16GB  512GB SSD             AMD Radeon Pro 455         macOS       1.83kg  2537.45        1
885        Samsung  Notebook 9                          Ultrabook           15.0    Full HD 1920x1080                           Intel Core i7 7500U 2.7GHz   16GB  256GB SSD             Nvidia GeForce 940MX       Windows 10  1.23kg  1849.00        1
945        HP       EliteBook 820                       Ultrabook           12.5    Full HD 1920x1080                           Intel Core i5 6200U 2.3GHz   4GB   500GB HDD             Intel HD Graphics 520      Windows 10  1.26kg  1579.00        1
940        Lenovo   Thinkpad X270                       Ultrabook           12.5    IPS Panel Full HD 1920x1080                 Intel Core i7 7500U 2.7GHz   8GB   256GB SSD             Intel HD Graphics 620      Windows 10  1.36kg  1650.00        1
938        Lenovo   ThinkPad Yoga                       2 in 1 Convertible  13.3    IPS Panel Full HD / Touchscreen 1920x1080   Intel Core i5 7200U 2.5GHz   8GB   512GB SSD             Intel HD Graphics 620      Windows 10  1.37kg  1825.00        1
                                                                                                                                                                                                                                                      ..
545        HP       Omen 15-ce006nv                     Gaming              17.3    Full HD 1920x1080                           Intel Core i7 7700HQ 2.8GHz  12GB  1TB HDD               Nvidia GeForce GTX 1060    Windows 10  2.62kg  1799.00        1
541        Asus     ROG Strix                           Gaming              15.6    IPS Panel Full HD 1920x1080                 Intel Core i5 7300HQ 2.5GHz  8GB   128GB SSD +  1TB HDD  Nvidia GeForce GTX 1060    Windows 10  2.3kg   1649.00        1
537        Dell     Alienware 17                        Gaming              17.3    IPS Panel Full HD 1920x1080                 Intel Core i7 7700HQ 2.8GHz  16GB  128GB SSD +  1TB HDD  Nvidia GeForce GTX 1070    Windows 10  4.42kg  3012.77        1
526        Asus     FX753VE-GC155T (i7-7700HQ/16GB/1TB  Gaming              17.3    Full HD 1920x1080                           Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD  Nvidia GeForce GTX1050 Ti  Windows 10  3kg     1504.00        1
1317       Lenovo   Yoga 900-13ISK                      2 in 1 Convertible  13.3    IPS Panel Quad HD+ / Touchscreen 3200x1800  Intel Core i7 6500U 2.5GHz   16GB  512GB SSD             Intel HD Graphics 520      Windows 10  1.3kg   1499.00        1
Name: count, Length: 326, dtype: int64

In [39]:
df_laptop[df_laptop['Price_euros']>1487].value_counts('Price_euros')

Price_euros
1799.0    14
1499.0    14
1899.0     7
1599.0     7
1749.0     7
          ..
1890.0     1
1891.0     1
1895.0     1
1903.0     1
6099.0     1
Name: count, Length: 221, dtype: int64